### ISSUE TITLE
Operation timed out while packaging

### ISSUE THREAD

**Issue by karthikg-09** [bentoml/comfy-pack#15]
Error to search using lite backend: https://lite.duckduckgo.com/lite/ RuntimeError: error sending request for url (https://lite.duckduckgo.com/lite/): operation timed out

Caused by:
    operation timed out
Error to search using html backend: https://html.duckduckgo.com/html RuntimeError: error sending request for url (https://html.duckduckgo.com/html): operation timed out

**Comment by parano** [comment]
@karthikg-09 could you be more specific where you ran into this issue and how to reproduce it?

**Comment by karthikg-09** [comment]
```Total VRAM 48670 MB, total RAM 515801 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA RTX A6000 : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: /workspace/ComfyUI/web
### Loading: ComfyUI-Manager (V2.55.5)
### ComfyUI Version: v0.3.9-13-g56bc64f3 | Released on '2024-12-22'
```
I am using ComfyUI via Cloudflare on runpod and trying to pack the default text to image workflow

**Comment by bojiang** [comment]
Thank you for reporting this issue @karthikg-09! You're right - this timeout problem occurs because our model retrieval currently depends on search engines, which can be problematic especially during first runs with multiple local models.
Long-term, we're planning to implement a public cache server to address this more thoroughly.
In the meantime, we'll improve the user experience by converting these errors to warnings, allowing the packaging process to complete even when some files can't be found.
Let us know if you continue to experience any issues!

**Comment by bojiang** [comment]
@karthikg-09  Hello. Which version of comfy-pack are you using? Would you like to re-try after updating comfy-pack from the Manager?

**Comment by karthikg-09** [comment]
> @karthikg-09 Hello. Which version of comfy-pack are you using? Would you like to re-try after updating comfy-pack from the Manager?

i am using the latest version of comfy-pack [06173ce](https://github.com/bentoml/comfy-pack/commit/06173cea47112adc9597a496e60b334db19bc4d2)

**Comment by bojiang** [comment]
@karthikg-09 Thank you for providing the detailed logs!
I can see that the package was created, but DuckDuckGo's rate limiting prevented us from fetching all model information. While this isn't ideal, your package should still work - you'll just need to manually search and download some models when using the workflow.
This rate limiting issue is something we're aware of. We plan to improve this with a more robust model information retrieval system in the future. For now, the missing model information won't affect the package's functionality.
Could you verify if you're able to find the generated package in your workspace?

**Comment by karthikg-09** [comment]
![image](https://github.com/user-attachments/assets/8cc8e643-8212-459f-99b7-46db828f6ba2)
it created a zip file in the temp folder after ~45 minutes, and the file size is huge—around 200mb. i just tried to package the basic text-to-image workflow. is this the packaged file, or am i missing something?
will it include my entire custom node with all the environment files, or just what’s visible in the workflow?

**Comment by bojiang** [comment]
@karthikg-09  
The 200MB should be because of the input folder. Including inputs folder is according to another user feedback.
Some workflows depends on some input files to work. If we want to ensure the reproduced envs is exactly the same, we have to restore input folder, too. But sometime it will be pretty large. I'm adding a input selector just like we did for models.

**Comment by karthikg-09** [comment]
OK thanks you for the clarification.. Is it possible to pack only the nodes, images and models present on the current workflow instead of packing everything?

**Comment by bojiang** [comment]
@karthikg-09  
Just like you said, the current version of comfy-pack marks and selects by default any models that are directly referenced in the workflow. We can have that for inputs in the future.

**Comment by karthikg-09** [comment]
in the next update, i hope to see the ability to pack only the models, images, and custom nodes that are present in the workflow, rather than packing everything. thank you

**Comment by bojiang** [comment]
@karthikg-09  Will let you know once we made progress

**Comment by bojiang** [comment]
https://github.com/bentoml/comfy-pack/pull/20/files input selector

**Comment by bojiang** [comment]
For the uv/pip issue, uv's default package resolving is more strict than pip. Will add make pip behavior the default and add a strict mode.
